[versions]
agp = "8.13.1"
kotlin = "2.2.21"
camerax = "1.6.2"
activity = "1.10.1"
junit = "4.13.2"

[libraries]
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity" }
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "camerax" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camerax" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camerax" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
